var numOptions = 04;
var answers = [];
var sel = new Array(numQues);
var attempts =0;
var numQues = 2;
var attempts = 0;
answers[0] = "She";answers[1] = "She";answers[2] = "He";answers[3] = "He";answers[4] = "He";answers[5] = "He";
answers[6] = "She";answers[7] = "He";answers[8] = "He";answers[9] = "She";answers[10] = "He";answers[11] = "He";
answers[12] = "He";answers[13] = "He";answers[14] = "She";answers[15] = "She";
answers[16] = "He";answers[17] = "He";answers[18] = "She";answers[19] = "She";answers[20] = "She";answers[21] = "He";
answers[22] = "He";answers[23] = "She";answers[24] = "She";answers[25] = "She";answers[26] = "She";answers[27] = "He";
answers[28] = "She";answers[29] = "He";answers[30] = "She";answers[31] = "He";
answers[32] = "She";answers[33] = "He";answers[34] = "He";answers[35] = "She";answers[36] = "She";
answers[37] = "She";answers[38] = "She";answers[39] = "She";answers[40] = "She";answers[41] = "She";answers[42] = "She";
answers[43] = "He";answers[44] = "He";
