var numOptions = 04;
var answers = [];
var sel = new Array(numQues);
var attempts =0;
var numQues = 2;
var attempts = 0;
answers[0] = "She";
answers[1] = "She";
answers[2] = "She";
answers[3] = "She";
answers[4] = "He";
answers[5] = "He";
answers[6] = "He";
answers[7] = "She";
answers[8] = "He";
answers[9] = "She";
answers[10] = "She";
answers[11] = "He";
answers[12] = "She";
answers[13] = "He";
answers[14] = "He";answers[15] = "She";
answers[16] = "He";answers[17] = "She";answers[18] =  "He";answers[19] = "She";answers[20] =  "She";answers[21] = "She";
